### ISSUE TITLE
Npm Start & Yarn Start Both Fail How do you run this example Locally?

### ISSUE THREAD

**Issue by Googolaire** [jscottsmith/react-scroll-parallax-examples#2]
I am trying to run this on my local environment after cloning it. With Npm I get 

huntermaxwell@Hunters-MacBook-Pro react-scroll-parallax-examples % npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/huntermaxwell/.npm/_logs/2020-02-15T16_12_18_670Z-debug.log
huntermaxwell@Hunters-MacBook-Pro react-scroll-parallax-examples % 

and with yarn I get

yarn run v1.22.0
(node:13985) ExperimentalWarning: The fs.promises API is experimental
error Command "start" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

How do you run this?

**Comment by jscottsmith** [comment]
Sorry, old project - updated to use parcel.
