### ISSUE TITLE
Examples outdated

### ISSUE THREAD

**Issue by Coteh** [jscottsmith/react-scroll-parallax-examples#3]
https://github.com/jscottsmith/react-scroll-parallax-examples/blob/e1f6d0397ce3c6f924324a43c5fd740131ad7edf/examples/parallax-example/components/TriangleGrid/TriangleGrid.js#L46-L49

Example uses outdated property values for `Parallax` component. Looks like there's a migration guide available that provides an upgrade path:

https://github.com/jscottsmith/react-scroll-parallax/blob/7aa6d3e26fd5ff4bc0ca461a47b42960f94dd47e/docs/migration-guide.md

**Comment by bonnopc** [comment]
Any update of this?

**Comment by jscottsmith** [comment]
updated ;)
